error.whitelabel.enabled: false
spring.jackson.serialization.INDENT_OUTPUT: true

server:
  port: 8080
  sessionTimeout: 0

xenqtt.connection.username: username
xenqtt.connection.password: password
xenqtt.connection.url: "tcp://mqtt.dev.mikael.io"
xenqtt.connection.port: 1883
xenqtt.connection.clientId: 1883
xenqtt.connection.cleanSession: false

xenqtt.subscriptions.list: test
xenqtt.subscriptions.QoS: 2

---
spring.profiles: test

server:
  port: 0
  address: 127.0.0.1
  sessionTimeout: 0

management.port: -1

spring:
  main:
    show-banner: false
    log-startup-info: true
  datasource:
    platform: h2
    url: "jdbc:h2:mem:"

logging.level:
  org.springframework: ERROR
  org.elasticsearch: ERROR
  org.hibernate: ERROR
  io.undertow: ERROR
  org.xnio: ERROR
  org.apache: ERROR
